plugins:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

Metrics/AbcSize:
  Max: 22

Metrics/CyclomaticComplexity:
  Max: 11

Metrics/MethodLength:
  Max: 18

Metrics/PerceivedComplexity:
  Max: 13

RSpec/MultipleMemoizedHelpers:
  Max: 6

RSpec/NestedGroups:
  Max: 4
